name: Test and Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Vectors
        run: |
          wget -q https://github.com/explosion/sense2vec/releases/download/v1.0.0/s2v_reddit_2015_md.tar.gz
          tar -xzf s2v_reddit_2015_md.tar.gz -C src
          rm s2v_reddit_2015_md.tar.gz

      - name: Docker Test
        run: |
          docker-compose --project-directory . -f docker/docker-compose.yml -f docker/docker-compose.test.yml \
          run app sh -c '. scripts/setup.sh && pytest'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Test Spec
        run: npx @stoplight/spectral lint docs/spec/openapi.yaml

      - name: Build Docs
        run: |
            npx redoc-cli bundle docs/spec/openapi.yaml --title 'spaCy Server'
            mkdir public
            mv redoc-static.html public/index.html
      
      - name: Publish To Github Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish on Docker Hub
        run: sh scripts/deploy.sh
        timeout-minutes: 120

